### PR TITLE
Add kelly's name and skills to README.md 

### PR DESCRIPTION
**Pull request by kdenisse29**

### CODE REVIEW

**Comment by dashaday** [comment]
Please correct some spelling errors: "but", "programming", "experience"

**Comment by wanminz** [comment]
Thank you so much for making my name a header!!!!

**Comment by dashaday** [comment]
Almost there! Please correct "I like JS ut" to "I like JS **but**" and put an "r" at the end on my last name. It's supposed to spell Hisoler. Thanks Kelly!

**Comment by kdenisse29** [comment]
Did it! this very old laptop keyboard sucks.

**Comment by kdenisse29** [comment]
just noticed it also changed the order! is that okay or go back and change it?

**Comment by dashaday** [comment]
LGTM. I feel like your keyboard is giving you a hard time so I'll fix any other error I see on my end! No need to change the order, it's totally fine.

**Comment by wanminz** [comment]
LGTM too!! 😁

**Pull request merged**
